import type { CSSProperties } from "react";

export const ui: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f5f6f8",
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    padding: "40px 16px",
    fontFamily: "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
    color: "#111",
  },
  shell: { width: "100%", maxWidth: 640 },
  card: {
    background: "#fff",
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: 24,
    boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
  },
  h1: { fontSize: 20, margin: "0 0 4px" },
  sub: { fontSize: 13.5, color: "#555", margin: "0 0 16px", lineHeight: 1.5 },
  row: { display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap", margin: "10px 0" },
  label: { display: "block", fontSize: 12, color: "#555", margin: "10px 0 4px" },
  input: {
    width: "100%",
    boxSizing: "border-box",
    padding: "10px 12px",
    border: "1px solid #d1d5db",
    borderRadius: 8,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 13,
  },
  btn: {
    padding: "9px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    background: "#fff",
    cursor: "pointer",
    fontSize: 14,
  },
  btnPrimary: {
    padding: "10px 16px",
    borderRadius: 8,
    border: "1px solid #111",
    background: "#111",
    color: "#fff",
    cursor: "pointer",
    fontSize: 14,
  },
  tabs: { display: "flex", gap: 6, margin: "0 0 14px" },
  tab: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #d1d5db",
    background: "#fff",
    cursor: "pointer",
    fontSize: 14,
  },
  tabActive: {
    padding: "8px 14px",
    borderRadius: 8,
    border: "1px solid #111",
    background: "#111",
    color: "#fff",
    cursor: "pointer",
    fontSize: 14,
  },
  mono: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", wordBreak: "break-all" },
  ok: {
    marginTop: 12,
    padding: "12px 14px",
    background: "#e7f6ec",
    border: "1px solid #b6e2c4",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
  },
  warn: {
    marginTop: 12,
    padding: "12px 14px",
    background: "#fff7e6",
    border: "1px solid #f0d38a",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
  },
  err: {
    marginTop: 12,
    padding: "12px 14px",
    background: "#fdecef",
    border: "1px solid #f2b8c2",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
    color: "#8a1020",
    wordBreak: "break-all",
  },
  info: {
    marginTop: 12,
    padding: "12px 14px",
    background: "#eef2ff",
    border: "1px solid #c7d2fe",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.5,
  },
  link: { color: "#1d4ed8", textDecoration: "none" },
  badge: {
    display: "inline-block",
    padding: "3px 8px",
    borderRadius: 999,
    fontSize: 12,
    border: "1px solid #d1d5db",
    background: "#f9fafb",
  },
};
